# Generated by Django 4.1.3 on 2022-12-05 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_wishlist_item_wishlist_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment",
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name="comments",
            name="commenter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commenter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comments",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentItem",
                to="auctions.listings",
            ),
        ),
    ]
