# Generated by Django 4.1.3 on 2022-12-05 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_comments_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(2022, 12, 6, 0, 2, 54, 151358)
            ),
        ),
    ]
