# Generated by Django 4.1.3 on 2022-12-06 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_comments_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(2022, 12, 6, 12, 53, 26, 275959)
            ),
        ),
    ]
